### ISSUE TITLE
Attach APK to releases?

### ISSUE THREAD

**Issue by IzzySoft** [blabbertabber/blabbertabber#71]
Could you please attach the APK file to its corresponding release (for folks without Playstore)? Thanks!

**Comment by cunnie** [comment]
Hi @IzzySoft.

I've added a step in our M&P's to upload the APK to GitHub when we cut a new release.

BlabberTabber is broken right now — IBM changed their API, which was a mixed blessing in that their diarizer is hard-coded to identifying 2 speakers. We're in the process of exploring alternative backends (of which Google is the frontrunner). In other words, you may want to wait a release or two before installing because as things stand BlabberTabber doesn't work.

—Brian

/cc @saintbrendan

**Comment by IzzySoft** [comment]
Thanks, @cunnie! Could you give me a ping when you think it's good enough?

**Comment by saintbrendan** [comment]
Ok.  Shall we work on this on Saturday?

**Comment by IzzySoft** [comment]
Just let me know when it's ready 😄 Furthermore also let me know if you want your app listed at [F-Droid](https://f-droid.org/), it seems to meet the inclusion criteria.

**Comment by IzzySoft** [comment]
@saintbrendan any news?

**Comment by IzzySoft** [comment]
Or should I have pinged @cunnie?

**Comment by IzzySoft** [comment]
@saintbrendan @cunnie which Saturday did you agree upon? Was it one of the 20+ that have passed meanwhile – or is it one of the next-to-come? Any chance?

**Comment by IzzySoft** [comment]
Well, no Sundays found it seems.

**Comment by cunnie** [comment]
@IzzySoft Hey, I wanted to get back to you—our software is completely broken. Not the Android portion, but the backend (diarizer) portion. The results it displays are basically random. We're going through a painstaking process of benchmarking the back-end diarizers, but between work and classes and rugby and swimming we've let this linger, maybe too long. We'll get to it, but when the backend is fixed.

**Comment by IzzySoft** [comment]
Hey @cunnie – now that's a statement I can understand :rofl: Good to see it has not been forgotten. Looking forward to that then – and I hope you won't feel annoyed if I ping for a refresh every now and then (in not too short intervals, promised).

**Comment by IzzySoft** [comment]
Had you success with the backend? Any hope for the APK turning up again? Maybe this issue should be reopened until fixed?

**Comment by cunnie** [comment]
@IzzySoft You can download the APK, but the backend is still broken.

**Comment by IzzySoft** [comment]
Thanks @cunnie – I've just re-enabled auto-update (and triggered it once to check it works). New version should show up with the next sync (in about 11 hours). Good luck with the backend then!

**Comment by cunnie** [comment]
@IzzySoft : I'm closing this issue because moving forward we'll release the APK to _both_ the Play Store and GitHub [releases](https://github.com/blabbertabber/blabbertabber/releases) (for folks without Play Store).

I want to compliment you on your persistence—we wouldn't have changed our publishing process without you.

Finally, I checked out your site—thanks for making the world a better place (or at least a more private place).

**Comment by IzzySoft** [comment]
> we'll release the APK to both the Play Store and GitHub releases (for folks without Play Store).

That's very good news, thanks! Also thanks for your kind words: seeing things accomplished in such good spirit is really encouraging to keep up my encouraging others :smiley:

PS: I just saw Synapsestorm (the bot in the #fdroid IRC channel at Freenode which checks several repos for updates) announcing the update of Blabbertabber, so everything worked out fine. As long as you keep tagging and attaching the APK to the tags, updates will flow!

So finally: all the best for your good work!
